tasks:
  - before: |
      sudo apt update
      sudo apt upgrade -y
      sudo apt autoremove --purge -y
      sudo apt install python3-venv python3-dev tree -y
      sudo apt install build-essential -y
  - init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -U pip
      pip install -U setuptools
      pip install -r requirements.txt
      python setup.py develop
  - command: |
      clear
      source venv/bin/activate
